---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app uptime-kuma
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    global:
      nameOverride: *app
    env:
      TZ: "${TIMEZONE}"
    image:
      repository: louislam/uptime-kuma
      tag: 1.21.1
    service:
      main:
        ports:
          http:
            port: 3001
    persistence:
      config:
        enabled: true
        existingClaim: uptime-kuma-pvc
        mountPath: /app/data
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: web-check
        hosts:
          - host: &host "status.${CLOUDFLARE_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    ressources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits: 150Mi
