---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./coredns/ks.yaml
  - ./external-secrets/ks.yaml
  - ./reloader/ks.yaml
  - ./metrics-server/ks.yaml
  - ./local-path-provisioner/ks.yaml
