---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-pgadmin
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cloudnative-pg
  path: ./kubernetes/apps/database/pgadmin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: nexus-repository
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
