---
data_dir: /vector-data-dir

sources:
  journal_logs:
    type: journald
    journal_directory: /var/log/journal

  kubernetes_logs:
    type: kubernetes_logs
    use_apiserver_cache: true
    pod_annotation_fields:
      container_image: container_image
      container_name: container_name
      pod_labels: pod_labels
      pod_name: pod_name
      pod_annotations: ""

sinks:
  loki_journald:
    type: vector
    compression: true
    version: "2"
    address: vector-aggregator.monitoring.svc.cluster.local:6000
    inputs:
      - journal_logs

  loki_kubernetes:
    type: vector
    compression: true
    version: "2"
    address: vector-aggregator.monitoring.svc.cluster.local:6010
    inputs:
      - kubernetes_logs
