---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-local-path-provisioner
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/disabled: "true"
spec:
  path: ./kubernetes/apps/kube-system/local-path-provisioner/app
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: nexus-repository
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: local-path-provisioner
      namespace: kube-system
