---
ansible:
  - "infrastructure/ansible/**/*"
terraform/aws:
  - "infrastructure/terraform/aws/*"
terraform/cloudflare:
  - "infrastructure/terraform/cloudflare/*"
terraform/github:
  - "infrastructure/terraform/github/*"
github-actions:
  - ".github/**/*"
