---
- name: File System | Disable swap at runtime
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: File System | Disable swap at boot
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none

- name: File System | Disable swap at boot
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop: ["none", "swap"]

- name: File System | System inotify Configuration using sysctls
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-kubernetes.conf
    reload: true
  with_dict: "{{ sysctl_config }}"
  vars:
    sysctl_config:
      fs.inotify.max_user_watches: 524288
      fs.inotify.max_user_instances: 512

- name: File System | NFS
  block:
    - name: NFS | Update configuration
      ansible.builtin.blockinfile:
        path: /etc/nfs.conf.d/local.conf
        mode: "0644"
        create: true
        block: |
          [nfsd]
          vers2 = n
          vers3 = n
          threads = 16

          [mountd]
          manage-gids = 1
