---
- name: Upgrade all system packages
  apt:
    upgrade: full
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_upgrade
  retries: 5
  until: apt_upgrade is success

- name: Install aptitude
  package:
    name: aptitude
    state: present
    update_cache: true

- name: Install packages list
  package:
    name: "{{ apt_install_packages }}"
    state: latest
    update_cache: true

- name: Remove packages
  block:
    - name: Remove packages
      apt:
        name: "{{ apt_remove_packages }}"
        state: absent
        autoremove: true
        autoclean: true

    - name: Clean files
      file:
        state: absent
        path: "{{ item }}"
      loop:
        - "/home/{{ ansible_user }}/.snap"
        - "/var/snap"
        - "/var/lib/snapd"
        - "/var/cache/snapd"
        - "/usr/lib/snapd"
      when:
        - "'snapd' in apt_remove_packages"
  when:
    - apt_remove_packages is defined
    - apt_remove_packages is iterable
    - apt_remove_packages | length > 0
