---
- name: User Configuration | Setup password less sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

- name: User Configuration | Set authorized key for remote user
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_ed25519.pub') }}"
  notify: Restart sshd

- name: User Configuration | Silence the login prompt
  ansible.builtin.file:
    dest: "/home/{{ ansible_user }}/.hushlogin"
    state: touch
    owner: "{{ ansible_user }}"
    mode: "0775"
    modification_time: preserve
    access_time: preserve
