---
- name: User Configuration | Add user to sudoers
  ansible.builtin.copy:
    content: "{{ ansible_user }} ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ ansible_user }}_nopasswd"
    mode: "0440"

- name: User Configuration | Silence the login prompt
  ansible.builtin.file:
    dest: "/home/{{ ansible_user }}/.hushlogin"
    state: touch
    owner: "{{ ansible_user }}"
    mode: "0775"
    modification_time: preserve
    access_time: preserve

- name: User Configuration | Fish shell
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/fish
