---
title: homelab
theme: dark
color: neutral
headerStyle: clean
hideVersion: true
layout:
  Monitoring:
    style: row
    icon: mdi-chart-line
    columns: 3
  Networking:
    style: row
    icon: mdi-wan
    columns: 1
