---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: portainer
      version: 1.0.40
      sourceRef:
        kind: HelmRepository
        name: portainer
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    enterpriseEdition: # free up to 5 nodes
      enabled: true
    service:
      type: ClusterIP
      httpPort: 9000
    persistence:
      enabled: true
      existingClaim: portainer-pvc
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: &host "cluster.${CLOUDFLARE_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    ressources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits: 70Mi
