---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - pvc.yaml
  - helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: portainer
      app.kubernetes.io/instance: portainer
