---
version: "3"

vars:
  ANSIBLE_DIR: "{{.ROOT_DIR}}/infrastructure/ansible"
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"

env:
  ANSIBLE_CONFIG: "{{.ANSIBLE_DIR}}/ansible.cfg"
  KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"

dotenv: [".envrc"]

includes:
  sops: ./.taskfiles/SopsTasks.yaml
  tf: ./.taskfiles/TerraformTasks.yaml
  flux: ./.taskfiles/FluxTasks.yaml
  pre-commit: ./.taskfiles/PrecommitTasks.yaml
  cluster: ./.taskfiles/ClusterTasks.yaml
  k8s: ./.taskfiles/Kubernetes.yaml
  secrets: ./.taskfiles/ExternalSecrets.yaml
tasks:
  default:
    silent: true
    cmds:
      - task -l
