---
version: "3"


dotenv: [".envrc"]

env:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes/{{.CLUSTER}}"
  KUBECONFIG: "{{.KUBERNETES_DIR}}/kubeconfig"


includes:
  sops: ./.taskfiles/SopsTasks.yaml
  flux: ./.taskfiles/FluxTasks.yaml
  pre-commit: ./.taskfiles/PrecommitTasks.yaml
  k8s: ./.taskfiles/Kubernetes.yaml
  secrets: ./.taskfiles/ExternalSecrets.yaml
tasks:
  default:
    silent: true
    cmds:
      - task -l
