---
version: "3"


dotenv: [".envrc"]

env:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes/{{.CLUSTER}}"
  KUBECONFIG: "{{.KUBERNETES_DIR}}/kubeconfig"


includes:
  sops: ./.taskfiles/sops/Taskfile.yaml
  flux: ./.taskfiles/flux/Taskfile.yaml
  pre-commit: ./.taskfiles/precommit/Taskfile.yaml
  kubernetes:
    aliases: ["k8s"]
    taskfile: ./.taskfiles/kubernetes/Taskfile.yaml
  secrets: ./.taskfiles/externalSecrets/Taskfile.yaml
tasks:
  default:
    silent: true
    cmds:
      - task -l
