---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: jenkins-secret
    deletionPolicy: Delete
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        jenkins-admin-user: "{{ .ADMIN_USER }}"
        jenkins-admin-password: "{{ .ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: jenkins
