---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
spec:
  interval: 30m
  chart:
    spec:
      chart: jenkins
      version: 5.7.6
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controller:
      admin:
        userKey: jenkins-admin-user
        passwordKey: jenkins-admin-password
        existingSecret: jenkins-secret
      jenkinsHome: "/var/jenkins_home"
      resources:
        requests:
          cpu: "50m"
          memory: "256Mi"
        limits:
          memory: "2096Mi"
      runAsUser: 1000
      fsGroup: 1000
      podSecurityContextOverride: ~
      containerSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
      serviceType: LoadBalancer
      healthProbes: true
      loadBalancerIP: "${SVC_JENKINS_ADDR}"
      ingress:
        enabled: true
        apiVersion: "networking.k8s.io/v1"
        ingressClassName: "internal"
        hostName: "jenkins.${CLUSTER_DOMAIN}"
        tls:
          - hosts:
              - "jenkins.${CLUSTER_DOMAIN}"
            secretName: "tls.${CLUSTER_DOMAIN/./-}"
