---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app minio
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2023-04-07T05-28-58Z
    env:
      TZ: "${TIMEZONE}"
      MINIO_UPDATE: "off"
      MINIO_BROWSER_REDIRECT_URL: http://minio.storage.svc.cluster.local:9000
      MINIO_SERVER_URL: http://s3.storage.svc.cluster.local:9000
    envFrom:
      - secretRef:
          name: minio-secret
    args:
      - server
      - /data
      - --console-address
      - :9001
    service:
      main:
        enabled: true
        ports:
          http:
            enabled: true
            port: &console-port 9001
          api:
            enalbed: true
            port: &api-port 9000
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /minio/health/live
            port: *api-port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &console-host "{{ .Release.Name }}.${CLOUDFLARE_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *console-port
        tls:
          - hosts:
              - *console-host
      s3:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
          nginx.ingress.kubernetes.io/proxy-body-size: 10240m
          nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            chunked_transfer_encoding off;
        hosts:
          - host: &api-host "s3.${CLOUDFLARE_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *api-port
        tls:
          - hosts:
              - *api-host
    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [1000]
    persistence:
      config:
        enabled: true
        existingClaim: minio-local-pvc
        mountPath: /data
    resources:
      requests:
        memory: 50Mi
        cpu: 50m
      limits:
        memory: 500Mi
