---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-busybox
  namespace: flux-system
spec:
  path: ./kubernetes/main/apps/debug/busy-box/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repository
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: busybox
      namespace: debug
  interval: 30m
  retryInterval: 1m
  timeout: 3m
