---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/provider_v1beta2.json
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: github-provider
  namespace: flux-system
spec:
  type: github
  address: https://github.com/unusualpseudo/Nexus
  interval: 10m
  secretRef:
    name: github-token-secret
