---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-coredns
  namespace: flux-system
  labels:
    substitution.flux/enabled: true
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: ./kubernetes/apps/kube-system/coredns/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: nexus-repository
