---
- name: Setup Cluster OS
  hosts: nexus
  any_errors_fatal: true
  gather_facts: true
  become: true
  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2
  roles:
    - os
