---
- name: Reboot all nodes
  hosts:
    - master
    - worker
  any_errors_fatal: true
  gather_facts: true
  become: true
  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2
  tasks:
    - name: Reboot and wait for node to come back up
      ansible.builtin.reboot:
        msg: Rebooting nodes
