---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-releoder
  namespace: flux-system
spec:
  path: ./kubernetes/apps/kube-system/reloader/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: nexus-repository
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      namespace: kube-system
      kind: HelmRelease
      name: reloader
  interval: 30m
  retryInterval: 1m
  timeout: 3m
