---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app vector-aggregator
  namespace: monitoring
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 2
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: timberio/vector
      tag: 0.30.0-debian
    args: ["--config", "/etc/vector/vector.yaml"]
    service:
      main:
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "vector.${CLOUDFLARE_DOMAIN}"
        externalIPs: ["${SVC_VECTOR_ADDR}"]
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8686
          journald:
            enabled: true
            port: 6000
          kubernetes:
            enabled: true
            port: 6010
    persistence:
      config:
        enabled: true
        type: configMap
        name: vector-aggregator-configmap
        subPath: vector.yaml
        mountPath: /etc/vector/vector.yaml
        readOnly: true
      data:
        enabled: true
        type: emptyDir
        mountPath: /vector-data-dir
