---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4-4
  storage:
    size: 20Gi
    storageClass: openebs-hostpath
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: 256MB
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  resources:
    requests:
      cpu: 30m
      memory: 256Mi
    limits:
      memory: 640Mi
  monitoring:
    enablePodMonitor: true
# Note: previousCluster needs to be set to the name of the previous
# cluster when recovering from an existing cnpg cluster
# bootstrap:
#   recovery:
#     source: &previousCluster postgres16-v5
# Note: externalClusters is needed when recovering from an existing cnpg cluster
# externalClusters:
#   - name: *previousCluster
#     barmanObjectStore:
#       <<: *barmanObjectStore
#       serverName: *previousCluster
