---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  annotations:
    io.cilium/lb-ipam-ips: ${SVC_POSTGRES_ADDR}
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    postgresql: postgres
    role: primary
