---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: botkube
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.botkube.io
