---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jetstack.yaml
  - ingress-nginx.yaml
  - metallb.yaml
  - metrics-server.yaml
  - stakater.yaml
  - bjw-s.yaml
  - calico.yaml
  - jameswynn.yaml
  - weave-gitops.yaml
  - portainer.yaml
  - kubernetes-dashboard.yaml
