---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: portainer
  namespace: flux-system
spec:
  interval: 30m
  url: https://portainer.github.io/k8s/
  timeout: 3m
