---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.6.2
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultSettings:
      defaultReplicaCount: 1
      createDefaultDiskLabeledNodes: true
      storageMinimalAvailablePercentage: 1
      storageReservedPercentageForDefaultDisk: 10
      defaultLonghornStaticStorageClass: longhorn
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      taintToleration: CriticalAddonsOnly:Exists; node-role.kubernetes.io/control-plane:NoSchedule
      orphanAutoDeletion: true
      backupTarget: s3://longhorn@eu-west-3/
      backupTargetCredentialSecret: longhorn-secret
      backupstorePollInterval: 0
    longhornUI:
      replicas: 1
    ingress:
      enabled: true
      ingressClassName: internal
      host: "longhorn.${CLUSTER_DOMAIN}"
      tls: true
    monitoring:
      enabled: true
      createPrometheusRules: true
