---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared
  namespace: networking
  annotations:
    external-dns.alpha.kubernetes.io/target: ingress.${CLOUDFLARE_DOMAIN}
spec:
  endpoints:
    - dnsName: ingress.${CLOUDFLARE_DOMAIN}
      recordType: CNAME
      targets: ["${CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"]
