---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cloudflared
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:


    image:
      repository: docker.io/cloudflare/cloudflared
      tag: 2023.6.1


    global:
      nameOverride: *app

    controller:
      replicas: 1
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"


    env:
      NO_AUTOUPDATE: "true"
      TUNNEL_CRED_FILE: /etc/cloudflared/creds/creds.json
      TUNNEL_METRICS: 0.0.0.0:8080
      TUNNEL_TRANSPORT_PROTOCOL: auto

    args:
      - tunnel
      - --config
      - /etc/cloudflared/config/config.yaml
      - run
      - "${CLOUDFLARE_TUNNEL_ID}"

    ingress:
      main:
        enabled: false

    service:
      main:
        nameOverride: metrics
        ports:
          http:
            port: 8080

    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 30s
    persistence:
      config:
        enabled: true
        readOnly: true
        defaultMode: 0755
        type: custom
        volumeSpec:
          configMap:
            name: &config cloudflared-config
        subPath:
          - path: config.yaml
            mountPath: /etc/cloudflared/config/config.yaml
            readOnly: true
      creds:
        enabled: true
        readOnly: true
        type: custom
        volumeSpec:
          secret:
            secretName: &secret cloudflared-secret
        subPath:
          - path: creds.json
            mountPath: /etc/cloudflared/creds/creds.json
            readOnly: true
    resources:
      requests:
        memory: 64Mi
        cpu: 10m
      limits:
        memory: 128Mi
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
      configmap.reloader.stakater.com/reload: *config
