---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-pihole
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-stores
  path: ./kubernetes/apps/networking/pihole/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: nexus-repository
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
