---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio-nfs
  labels:
    isk.home.arpa/fs: zfs
    disk.home.arpa/type: hdd
provisioner: nfs.csi.k8s.io
parameters:
  server: ${NFS_SERVER_ADDR}
  share: /nfs-pool/Apps/MinioIO
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.2
  - nconnect=8
  - hard
  - noatime
