---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: csi-driver-nfs
    meta.helm.sh/release-namespace: kube-system
  labels:
    app.kubernetes.io/name: csi-driver-nfs
    app.kubernetes.io/instance: nfs-direct
  name: nfs-direct
provisioner: nfs.csi.k8s.io
parameters:
  server: ${NFS_SERVER_ADDR}
  share: ${NFS_BASE_PATH}
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.2
  - nconnect=8
  - hard
