---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        CLUSTER_DOMAIN: "{{ .CF_CLUSTER_DOMAIN }}"
        PIHOLE_API_KEY: "{{ .PIHOLE_API_KEY }}"
        LATITUDE: "{{ .HOMEPAGE_LATITUDE }}"
        LONGITUDE: "{{ .HOMEPAGE_LONGITUDE }}"
  dataFrom:
    - extract:
        key: cloudflare
    - extract:
        key: pihole
    - extract:
        key: homepage
