# https://github.com/Tzahi12345/YoutubeDL-Material/blob/master/docker-compose.yml
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: youtubedl
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      youtubedl:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/tzahi12345/youtubedl-material
              tag: 4.3.2
            env:
              TZ: ${TIMEZONE}
              write_ytdl_config: true
    service:
      app:
        controller: youtubedl
        ports:
          http:
            port: &port 17442
    ingress:
      app:
        className: internal
        hosts:
          - host: "yt.${CLUSTER_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: *port
    persistence:
      config:
        enabled: true
        existingClaim: youtubedl
        globalMounts:
          - path: /config
      media:
        enabled: true
        type: nfs
        server: ${NFS_MAIN_SERVER_ADDR}
        path: "${NFS_MEDIA_FOLDER}/YouTube"
        globalMounts:
          - path: /app/video
