---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pihole
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pihole-secret
    creationPolicy: Owner
  data:
    - secretKey: adminPassword
      remoteRef:
        key: pihole
        property: adminPassword
