---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-botkube
  namespace: flux-system
spec:
  path: ./kubernetes/main/apps/monitoring/botkube/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repository
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: botkube
      namespace: monitoring
  interval: 30m
  retryInterval: 2m
  timeout: 2m
