---

storage:
  type: postgres
  path: postgres://${INIT_POSTGRES_USER}:${INIT_POSTGRES_PASS}@${INIT_POSTGRES_HOST}:5432/${INIT_POSTGRES_DBNAME}?sslmode=disable
  caching: true

metrics: true

ui:
  title: Status | Gatus
  header: Status

alerting:
  pushover:
    application-token: ${PUSHOVER_APP_TOKEN}
    user-key: ${PUSHOVER_USER_KEY}
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 5
      success-threshold: 2

connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 5m

endpoints:
  - name: grafana
    group: external
    url: https://grafana.${CLOUDFLARE_DOMAIN}/api/health
    interval: 5m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover

  - name: homepage
    group: external
    url: https://homepage.${CLOUDFLARE_DOMAIN}
    interval: 5m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover

  - name: echo-server
    group: external
    url: https://echo-server.${CLOUDFLARE_DOMAIN}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover
