---

storage:
  type: postgres
  path: postgres://${INIT_POSTGRES_USER}:${INIT_POSTGRES_PASS}@${INIT_POSTGRES_HOST}:5432/${INIT_POSTGRES_DBNAME}?sslmode=disable
  caching: true

metrics: true

ui:
  title: Status | Gatus
  header: Status

alerting:
  pushover:
    application-token: ${PUSHOVER_APP_TOKEN}
    user-key: ${PUSHOVER_USER_KEY}
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 5
      success-threshold: 2

connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints:
  - name: grafana
    group: external
    url: https://grafana.${CLOUDFLARE_DOMAIN}/api/health
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover

  - name: homepage
    group: external
    url: https://homepage.${CLOUDFLARE_DOMAIN}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover

  - name: echo-server
    group: external
    url: https://echo-server.${CLOUDFLARE_DOMAIN}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover

  - name: portainer
    group: internal
    url: 1.1.1.1
    interval: 1m
    dns:
      query-name: portainer.${CLOUDFLARE_DOMAIN}
      query-type: A
    conditions:
      - "len([BODY]) == 0"
    alerts:
      - type: pushover


  - name: gitops
    group: internal
    url: 1.1.1.1
    interval: 1m
    dns:
      query-name: gitops.${CLOUDFLARE_DOMAIN}
      query-type: A
    conditions:
      - "len([BODY]) == 0"
    alerts:
      - type: pushover


  - name: pihole
    group: internal
    url: 1.1.1.1
    interval: 1m
    dns:
      query-name: pihole.${CLOUDFLARE_DOMAIN}
      query-type: A
    conditions:
      - "len([BODY]) == 0"
    alerts:
      - type: pushover


  - name: kubernetes
    group: internal
    url: 1.1.1.1
    interval: 1m
    dns:
      query-name: kubernetes.${CLOUDFLARE_DOMAIN}
      query-type: A
    conditions:
      - "len([BODY]) == 0"
    alerts:
      - type: pushover


  - name: pgadmin
    group: internal
    url: 1.1.1.1
    interval: 1m
    dns:
      query-name: pgadmin.${CLOUDFLARE_DOMAIN}
      query-type: A
    conditions:
      - "len([BODY]) == 0"
    alerts:
      - type: pushover


  - name: minio
    group: internal
    url: 1.1.1.1
    interval: 1m
    dns:
      query-name: minio.${CLOUDFLARE_DOMAIN}
      query-type: A
    conditions:
      - "len([BODY]) == 0"
    alerts:
      - type: pushover


  - name: longhorn
    group: internal
    url: 1.1.1.1
    interval: 1m
    dns:
      query-name: longhorn.${CLOUDFLARE_DOMAIN}
      query-type: A
    conditions:
      - "len([BODY]) == 0"
    alerts:
      - type: pushover


  - name: lldap
    group: internal
    url: 1.1.1.1
    interval: 1m
    dns:
      query-name: lldap.${CLOUDFLARE_DOMAIN}
      query-type: A
    conditions:
      - "len([BODY]) == 0"
    alerts:
      - type: pushover
