---
data_dir: /vector-data-dir

api:
  enabled: true
  address: 0.0.0.0:8686

#
# Sources
#
sources:
  journal_logs:
    type: vector
    version: "2"
    address: 0.0.0.0:6000

  kubernetes_logs:
    type: vector
    version: "2"
    address: 0.0.0.0:6010

#
# Transforms
#
transforms:
  kubernetes_logs_remap:
    type: remap
    inputs:
      - kubernetes_logs
    source: |
      # Standardize 'app' index
      .custom_app_name = .pod_labels."app.kubernetes.io/name" || .pod_labels.app || .pod_labels."k8s-app" || "unknown"
#
# Sinks
#
sinks:
  loki_journal:
    inputs:
      - journal_logs
    type: loki
    endpoint: http://loki-gateway.monitoring.svc.cluster.local
    encoding:
      codec: json
    out_of_order_action: accept
    remove_label_fields: true
    remove_timestamp: true
    labels:
      hostname: '{{ host }}'

  loki_kubernetes:
    inputs:
      - kubernetes_logs_remap
    type: loki
    endpoint: http://loki-gateway.monitoring.svc.cluster.local
    encoding:
      codec: json
    out_of_order_action: accept
    remove_label_fields: true
    remove_timestamp: true
    batch:
      max_bytes: 2049000
    labels:
      app: '{{ custom_app_name }}'
      container_name: '{{ container_name }}'
      namespace: '{{ kubernetes.pod_namespace }}'
      node: '{{ kubernetes.pod_node_name }}'
