---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/instance: authelia
      app.kubernetes.io/name: authelia
configMapGenerator:
  - name: authelia-configmap
    files:
      - ./config/configuration.yaml
generatorOptions:
  disableNameSuffixHash: true
patchesStrategicMerge:
  - /patches/env.yaml
