---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # https://github.com/onedr0p/flux-cluster-template/issues/321 : patch needed
  - ./tigera-operator/ks.yaml
