---
- name: Assert params are not empty
  assert:
    that:
      - username != ''
      - password != ''
    fail_msg: "Params must not be empty or null!"

- name: "Create a user {{ username }} with sudo privileges"
  user:
    name: "{{ username }}"
    state: present
    shell: /bin/bash
    groups: sudo
    password: "{{ password | password_hash('sha512') }}"
    createhome: true
    generate_ssh_key: true
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Set authorized key for remote user
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
  notify: Restart sshd

- name: Setup password less sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
