---
- name: K3s reset
  hosts: nexus
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2
  roles:
    - reset
  post_tasks:
    - name: Reboot and wait for node to come back up
      reboot:
        reboot_timeout: 3600
