---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-echo-server
  namespace: flux-system
spec:
  path: ./kubernetes/main/apps/networking/echo-server/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repository
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: echo-server
      namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 3m
