---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-pihole
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: external-dns-pihole-secret
    creationPolicy: Owner
  data:
    - secretKey: pihole-password
      remoteRef:
        key: pihole
        property: adminPassword
