---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-flux-notifications
  namespace: flux-system
spec:
  path: ./kubernetes/main/apps/flux-system/notifications
  dependsOn:
    - name: cluster-apps-external-secrets-stores
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repository
  interval: 30m
  retryInterval: 1m
  timeout: 3m
