---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-echo-server
  namespace: flux-system
spec:
  path: ./kubernetes/apps/debug/echo-server/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: nexus-repository
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: echo-server
      namespace: debug
  interval: 30m
  retryInterval: 1m
  timeout: 3m
