---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-dnsutils
  namespace: flux-system
spec:
  path: ./kubernetes/apps/debug/dnsutils/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: nexus-repository
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: dnsutils
      namespace: debug
  interval: 30m
  retryInterval: 1m
  timeout: 3m
