---
- Infrastructure:
    - Pihole:
        href: http://192.168.1.105/admin
        icon: https://static-00.iconduck.com/assets.00/pihole-icon-174x256-w2exgm2v.png
        description: DNS Server
        ping: 192.168.1.105
        siteMonitor: http://192.168.1.105
        widget:
          type: pihole
          url: http://192.168.1.105/
          key: {{PIHOLE_API_KEY}}

- Observability:
    - Gatus:
      href: https://status.{{CLUSTER_DOMAIN}}.com/
      icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT50mSXT9rej_qhHTtQplLjf63bfhnZpQoh2A&s
      description: Status Page
      widget:
        type: gatus
        url: https://status.{{CLUSTER_DOMAIN}}/
