---
title: Dashboard
favicon: https://w7.pngwing.com/pngs/848/762/png-transparent-computer-icons-home-house-home-angle-building-rectangle-thumbnail.png
useEqualHeights: true
theme: dark
background:
  image: https://i.imgur.com/oFw7T7g.jpg
  opacity: 20
color: slate
headerStyle: clean
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
layout:
  Infrastructure:
    style: row
    columns: 3
    icon: mdi-server
