---
- logo:
    icon: https://sundayguardianlive.com/wp-content/uploads/2020/07/Untitled-design-9.png
- search:
    provider: [google]
    focus: false
    target: _blank
- greeting:
    text_size: xl
    text: "Hey how are you doing today?"
- kubernetes:
    cluster:
      cpu: true
      memory: true
      show: true
      showLabel: true
    nodes:
      cpu: true
      memory: true
      show: false
      showLabel: true
- openmeteo:
    label: Home
    latitude: {{LATITUDE}}
    longitude: {{LONGITUDE}}
    timezone: Europe/Paris
    units: metric
    cache: 5
    format:
      maximumFractionDigits: 1
