---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-minio
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-stores
  path: ./kubernetes/apps/storage/minio/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: nexus-repository
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: minio
      namespace: storage
  interval: 30m
  retryInterval: 1m
  timeout: 3m
