---
title: Nexus
theme: dark
background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
color: slate
headerStyle: clean
hideVersion: true
layout:
  Monitoring:
    style: row
    columns: 1
    icon: mdi-chart-line
  Cloud:
    style: row
    columns: 2
  Git:
    style: row
    columns: 2
  Media:
    style: row
    columns: 2
    icon: mdi-play-circle
  Social:
    style: row
    columns: 2
    icon: mdi-play-circle
