---
- search:
    provider: google
    focus: false
    target: _blank
- greeting:
    text_size: xl
    text: "Hey Space Cowboy!"
- kubernetes:
    cluster:
      cpu: true
      label: cluster
      memory: true
      show: true
      showLabel: true
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true
- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
      hourCycle: h23
