---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${CLOUDFLARE_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: "${CLOUDFLARE_EMAIL}"
            apiKeySecretRef:
              name: cloudflare-secret
              key: apiKey
        selector:
          dnsZones:
            - "${CLOUDFLARE_DOMAIN}"
