---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: spik3spiegel@proton.me
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: spik3spiegel@proton.me
            apiKeySecretRef:
              name: cert-manager-secret
              key: api-key
        selector:
          dnsZones:
            - falsebit.io
