apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:Dk2BmmRz1TwcArUe9DVMCBiNkk9hO9haTmdyXDOYoMerDAu+bA==,iv:EU3cEAo3tvIJ5uc402ztj9eAhAE/qIvNN9eS+kIwTtU=,tag:YFkbe2PoLRj3Y9wtKHoVqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zqydytfsqv3g789ud2jjhrflk445wcadnz0fccrf82zhwfwcgd4q404rtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvM3NUV0V5WS9wTE9laHJx
            eGZNUkdrSzExNTAxWXB5aDRWY05sZW1RRjBRClZndzRoUjBtZnVLMHB6WGkxMFdW
            cHAvNTdxUDMzbE9vS2l3OWdDWS8zK00KLS0tIFEyUWkxalJsbXB5V0RBKy8xWFNQ
            N0tPSE1FU2ZkNWJKa2lrNUVBTktOOWsKlXTXOsFUAgyRWRITCnBPwsaW1K3tqSkT
            slAc5+FVw5WNFVeZoC1XWRH8Xt0omszq+/aGFkHVzUno30K6n0TDvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-25T21:34:26Z"
    mac: ENC[AES256_GCM,data:bUPJ6drFhwdQpHKM2GkrA+KXt0LWKwgc6C46bao5F1AdMy6ZAx+mo11ArWmT51ZMsi+zqF9G+rVkr9ENiXi16BzjFZ+zIUWy7LaawJjVeW0XQv5i16Zp8kMK814ka3HZ/+8i9myzuCntjXOx8vGMj14A1fjRxNsqZPgqarxMKLA=,iv:WtCV12+lgO0u6JwfHrjKvgVQOllp8ack1eXS7iO8/Bo=,tag:hWvlWHzHcNQml1j0c3aPHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
