---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app external-dns
  namespace: networking
spec:
  interval: 30m
  releaseName: *app
  chart:
    spec:
      chart: external-dns
      version: 1.12.2
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    logLevel: debug
    interval: 2m
    provider: cloudflare
    policy: sync
    txtPrefix: "k8s."
    sources:
      - ingress
    domainFilters:
      - "${CLOUDFLARE_DOMAIN}"
    env:
      - name: CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            name: external-dns-secret
            key: email
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            name: external-dns-secret
            key: api-key
    extraArgs:
      - --cloudflare-proxied
      - --annotation-filter=external-dns.alpha.kubernetes.io/target
    rbac:
      additionalPermissions:
        - apiGroups: ["externaldns.k8s.io"]
          resources: ["dnsendpoints"]
          verbs: ["get", "watch", "list"]
        - apiGroups: ["externaldns.k8s.io"]
          resources: ["dnsendpoints/status"]
          verbs: ["*"]
    resources:
      requests:
        memory: 100Mi
        cpu: 25m
      limits:
        memory: 250Mi
    podAnnotations:
      secret.reloader.stakater.com/reload: external-dns-secret
