---
session:
  redis:
    high_availability:
      sentinel_name: redis-master
      nodes:
        - host: redis-node-0.redis-headless.database.svc.cluster.local
          port: 26379
        - host: redis-node-1.redis-headless.database.svc.cluster.local
          port: 26379

access_control:
  default_policy: two_factor
  networks:
    - name: internal
      networks: ["192.168.1.0/24"]
