---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-loki
  namespace: flux-system
spec:
  path: ./kubernetes/apps/monitoring/loki/app
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-longhorn
  prune: true
  sourceRef:
    kind: GitRepository
    name: nexus-repository
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
