kind: Secret
cloudflare_email: ENC[AES256_GCM,data:jFM5UtDFx5d5ZMEVY0uJr5TBAix7/g==,iv:BjeYBSUP2+pG7ayYr85DoLW95JSBdDJPqQoXkWbint0=,tag:dlT75OyZEDFL8vfjftQ8tQ==,type:str]
cloudflare_api_key: ENC[AES256_GCM,data:Ea0Wa8l3zNd+Z635Ia0syI/2K6SvshWdNgL87cJWuWB3i4KApw==,iv:hAVUA0upAoIvihWms1l6Kd0McdM74bgAie79PshLjq4=,tag:sTRgonRs8kDZVFu3n7Wlsw==,type:str]
cloudflare_domain: ENC[AES256_GCM,data:EMxBDNczMXoBF04=,iv:u71y7tMky/vlhRnx/8unMeDGNeZ2uO21r3p6JW3w4v4=,tag:xuY45ttkavyhFswtFKNI9w==,type:str]
country: ENC[AES256_GCM,data:XrA=,iv:G4yyhZXpRLqtOfjFGR7oyz8eC1zvNkMpqG+EL8x3BhY=,tag:uz9UJ/dlGTYMlj1dWdQ/rA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zqydytfsqv3g789ud2jjhrflk445wcadnz0fccrf82zhwfwcgd4q404rtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2YzNJc2ovTkh4cHRmNGR2
            MnE2MExkcmh1SURZUWhabFY3ZUVSajhRSldzClVWK0FwMVhGRlBZMzRTaStiUlRs
            UnI2TURkdUxQVnlXNnNBZkErQlM4S0UKLS0tIFRHR1lMZ21vcFQvTURpUDRoeE9n
            RFpubFVaNkFRRGx4VDZhODU0ZUp0Y28KTLpf9HysIZ0MQ0Oc5yhfXicutSiBLxTn
            oY39WTmO06WAX8EI7WAdOFNM09qqH9YuxEjzyXkRhH1ezSIEO3uDGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-17T20:35:37Z"
    mac: ENC[AES256_GCM,data:p3SrghzKFusLay7s8DmIN6ZrK5JBk7C78mMAqrXa8mUHlsAH6cv3qyJlnTQCyhRqJQMsC3/wbi2hX0YDPHZBNWSXstjgzPrA2trRMoqye0hihxkjF7O7N1MzzpyylXyHcovh1cc28sN/JUIM6rwk7swoOn7d8/dLL3n9f5f7c/8=,iv:muoS3Kz/4L2RNyplqhXjcp1gnxPmi9ZDZOlN6RlEnUw=,tag:7gJ1kLYfqbicHEL50semxQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
