---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cloudflared
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/cloudflared/app
  dependsOn:
    - name: cluster-apps-external-secrets-stores
  prune: true
  sourceRef:
    kind: GitRepository
    name: nexus-repository
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cloudflared
      namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 3m
