---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dnsutils
  namespace: debug
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  maxHistory: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        enabled: false
    image:
      repository: gcr.io/kubernetes-e2e-test-images/jessie-dnsutils
      tag: "1.0"
    command:
      - sleep
      - "3600"
