---
# yaml-language-server: $schema=https://kochhaus-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls.harbor
spec:
  dnsNames:
    - harbor.${CLUSTER_DOMAIN}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: tls.harbor
  usages:
    - digital signature
    - key encipherment
