---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: harbor-secret
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        HARBOR_ADMIN_PASS: harbor
        # Postgres Init
        INIT_POSTGRES_DBNAME: harbor
        INIT_POSTGRES_USER: "{{ .HARBOR_DB_USER }}"
        INIT_POSTGRES_PASS: "{{ .HARBOR_DB_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
  dataFrom:
    - extract:
        key: harbor
    - extract:
        key: cloudnative-pg
