---
- name: K3s Cluster Install
  hosts:
    - master
    - worker
  any_errors_fatal: true
  become: true
  gather_facts: true

  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2

  tasks:
    - name: Check if k3s is installed
      ansible.builtin.stat:
        path: /etc/rancher/k3s/config.yaml
      register: k3s_check_installed
      check_mode: false

    - name: Set manifest facts
      ansible.builtin.set_fact:
        k3s_server_manifests_templates: []
        k3s_server_manifests_urls: []
      when: k3s_check_installed.stat.exists

    - name: Install Kubernetes
      ansible.builtin.include_role:
        name: xanmanning.k3s
        public: true
      vars:
        k3s_state: installed

    - name: Resource Readiness Check
      kubernetes.core.k8s_info:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        kind: "{{ item.kind }}"
        name: "{{ item.name }}"
        namespace: "{{ item.namespace | default('') }}"
        wait: true
        wait_sleep: 10
        wait_timeout: 360
      loop:
        - kind: Deployment
          name: tigera-operator
          namespace: tigera-operator
        - kind: Installation
          name: default
        - kind: HelmChart
          name: coredns
          namespace: kube-system
      register: resource_check
      when:
        - k3s_server_manifests_templates | length > 0
          or k3s_server_manifests_urls | length > 0
        - k3s_control_node is defined
        - k3s_control_node

    - name: Remove deployed manifest templates
      ansible.builtin.file:
        path: "{{ k3s_server_manifests_dir }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
        state: absent
      loop: "{{ k3s_server_manifests_templates | default([]) }}"

    - name: Remove deployed manifest urls
      ansible.builtin.file:
        path: "{{ k3s_server_manifests_dir }}/{{ item.filename }}"
        state: absent
      loop: "{{ k3s_server_manifests_urls | default([]) }}"

    - name: Coredns
      when:
        - k3s_primary_control_node
        - (k3s_server_manifests_templates | length > 0
          or k3s_server_manifests_urls | length > 0)
      ansible.builtin.include_tasks: tasks/coredns.yaml

    - name: Stale contrainers
      ansible.builtin.include_tasks: tasks/stale_containers.yaml
      vars:
        stale_containers_state: enabled
