---
- name: Setup Cluster OS and Reboot
  hosts:
    - master
    - worker
  any_errors_fatal: true
  gather_facts: true
  become: true

  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2

  tasks:
    - name: Execute OS tasks
      block:
        - name: Run OS role tasks
          ansible.builtin.include_role:
            name: os
