---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-csi-driver-nfs
  namespace: flux-system
spec:
  path: ./kubernetes/main/apps/kube-system/csi-driver-nfs/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repository
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: csi-driver-nfs
      namespace: kube-system
  interval: 15m
  retryInterval: 1m
  timeout: 3m
