---
originRequest:
  originServerName: "external.${CLOUDFLARE_DOMAIN}"

ingress:
  - hostname: "${CLOUDFLARE_DOMAIN}"
    service: https://nginx-external-controller.network.svc.cluster.local:443
  - hostname: "*.${CLOUDFLARE_DOMAIN}"
    service: https://nginx-external-controller.network.svc.cluster.local:443
  - service: http_status:404
