---
# Docs: https://www.kubecost.com/kubernetes-autoscaling/kubernetes-vpa/
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpa
  namespace: observability
spec:
  interval: 15m
  chart:
    spec:
      chart: vpa
      version: 1.7.1
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
  timeout: 20m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    recommender:
      enabled: true
    image:
      repository: registry.k8s.io/autoscaling/vpa-recommender
      tag: 0.13.0
    resources:
      requests:
        cpu: 15m
        memory: 145M
      limits:
        memory: 174M
      extraArgs:
        pod-recommendation-min-cpu-millicores: 15
        pod-recommendation-min-memory-mb: 61
    updater:
      enabled: false
    admissionController:
      enabled: false
