---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-metallb
  namespace: flux-system
spec:
  path: ./kubernetes/main/apps/networking/metallb/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repository
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: metallb
      namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-metallb-config
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-metallb
  path: ./kubernetes/main/apps/networking/metallb/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repository
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
