---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-gatus
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cloudnative-pg-cluster
    - name: cluster-apps-external-secrets-stores
  path: ./kubernetes/main/apps/monitoring/gatus/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repository
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
