---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-vector
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/monitoring/vector/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: nexus-repository
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
