---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homepage
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: homepage
      version: 1.1.1
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/benphelps/homepage
      tag: v0.6.10
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        ports:
          http:
            port: 3000
            targetPort: 3000
    enableRbac: true
    serviceAccount:
      create: true
      name: homepage
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${CLOUDFLARE_DOMAIN}"
        hosts:
          - host: &host "homepage.${CLOUDFLARE_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podAnnotations:
      configmap.reloader.stakater.com/reload: *app
    config:
      useExistingConfigMap: *app
