---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # How to run it : https://github.com/haraldkoch/kochhaus-home/tree/main/cluster/core/kube-system/coredns
  - helmrelease.yaml
