---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./coredns.yaml
  - ./jetstack.yaml
  - ./ingress-nginx.yaml
  - ./metrics-server.yaml
  - ./stakater.yaml
  - ./bjw-s.yaml
  - ./jameswynn.yaml
  - ./external-secrets.yaml
  - ./external-dns.yaml
  - ./prometheus-community.yaml
  - ./grafana.yaml
  - ./cloudnative-pg.yaml
  - ./runix.yaml
  - ./cilium.yaml
  - ./openebs.yaml
  - ./longhorn.yaml
  - ./spark-operator.yaml
  - ./jenkins.yaml
