---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.17
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    adminUser:
      create: true
      username: admin
    envVars:
      - name: WEAVE_GITOPS_FEATURE_TENANCY
        value: "false"
    ingress:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        external-dns.alpha.kubernetes.io/target: "${CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"
      hosts:
        - host: &host "gitops.${CLOUDFLARE_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    networkPolicy:
      create: true
    metrics:
      enabled: true
    rbac:
      create: true
      impersonationResourceNames: ["admin"]
    podAnnotations:
      secret.reloader.stakater.com/reload: weave-gitops-secret
  valuesFrom:
    - kind: Secret
      name: weave-gitops-secret
      valuesKey: adminPasswordHash
      targetPath: adminUser.passwordHash
