---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-grafana
  namespace: flux-system
spec:
  path: ./kubernetes/main/apps/monitoring/grafana/app
  dependsOn:
    - name: cluster-apps-external-secrets-stores
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repository
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: grafana
      namespace: monitoring
  interval: 15m
  retryInterval: 1m
  timeout: 5m
