---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${APP}"
spec:
  accessModes: ["${VOLUME_ACCESSMODES:-ReadWriteOnce}"]
  resources:
    requests:
      storage: "${VOLUME_CAPACITY}"
  storageClassName: "${VOLUME_STORAGECLASS:-longhorn}"
