kind: Secret
bucket_name: ENC[AES256_GCM,data:s+Rhf4lXDAHQiG/ryNcF,iv:xRa3DVFPbTtJN1YEGaPBxLz1DyUQyRHanou5fdHFniA=,tag:85g9Si25lknBO7WaiNAuqg==,type:str]
notify_email: ENC[AES256_GCM,data:J69psL1Nxb/8hj8g3UZmQyw5ZkqMlA==,iv:tkvNiZArvxLQkV0DqvodIBCES51G+AXAWJNvOjJuVMI=,tag:mzMfepPpvLV5zEt72I95NA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zqydytfsqv3g789ud2jjhrflk445wcadnz0fccrf82zhwfwcgd4q404rtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdHhNKzh1emRvU0JSUExD
            Vmhvb3ZQOVM0UkE2VXJYWFlXRkZrSWlKZldRCmZLMnk1OUNrREthUStQUzdXQ21u
            Y3AyNGZjczRUUnNHS2llcG51aDNPdWMKLS0tIDJGUUVreWtaNEcwNmh3VCt1UnVw
            ZmFhTlpCdDdDZ1hOTE95K09Ob3JaWW8KJUTC8sVHWjbWt55UmnCNe5OANlHwzOqC
            rgIlLqydQe0VQ4CKS9VhZTgsAQm6lMWS5Eip3ODPcy1Kc7+L/gBLQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-17T21:10:09Z"
    mac: ENC[AES256_GCM,data:coUVcXUwBCEqgwv6xdpWoZHkA3R6JL4EV+sYz5q4pQd9Ca+cT/N0VgyrOKH57SQWrlpGhrYsF8nxzLAFFgwdbcHLGJSxdxu45+uhcu4bFTjSvo9CyRQttH1tslwWnpa0PBunn5A6vO/brkNZLuL33Ue8NxNWl96TmVal3icYCo4=,iv:AXO8OA84AVIrmXPFU7H3ITru6zLUqID+4Xayt/DVCg4=,tag:IWs2rWQ5Ig9PU2F9fS6esA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
