---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-coredns
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: ./kubernetes/main/apps/kube-system/coredns/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: homelab-repository
