---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-vpa
  namespace: flux-system
spec:
  path: ./kubernetes/apps/observability/vpa/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: nexus-repository
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: vpa
      namespace: observability
  interval: 30m
  retryInterval: 1m
  timeout: 3m
