---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: observability
spec:
  interval: 15m
  chart:
    spec:
      chart: goldilocks
      version: 6.5.2
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
  timeout: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    controller:
      resources:
        requests:
          cpu: 20m
          memory: 145M
        limits:
          cpu: null
          memory: 150M
    dashboard:
      replicaCount: 1
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host "goldilocks.${CLOUDFLARE_DOMAIN}"
            paths:
              - path: /
                type: Prefix
        tls:
          - hosts:
              - *host
    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        memory: 64M
