---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: botkube-discord
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: botkube-discord-secret
    creationPolicy: Owner
  data:
    - secretKey: botId
      remoteRef:
        key: discord
        property: botkubeId
    - secretKey: token
      remoteRef:
        key: discord
        property: botkubeToken
    - secretKey: channelId
      remoteRef:
        key: discord
        property: botkubeChannelId
