---
- name: Template module to interpolate variables and copy the file
  template:
    src: calico-installation.yaml.j2
    dest: calico-installation.yaml

- name: Install Calico
  command: kubectl create -f {{ item }}
  loop:
    - https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/tigera-operator.yaml
    - calico-installation.yaml

- name: Delete Calico manifest
  become_user: "{{ ansible_user }}"
  file:
    path: calico-installation.yaml
    state: absent

- name: Resource Readiness Check
  run_once: true
  kubernetes.core.k8s_info:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    kind: "{{ item.kind }}"
    name: "{{ item.name }}"
    namespace: "{{ item.namespace | default('') }}"
    wait: true
    wait_sleep: 10
    wait_timeout: 360
  loop:
    - kind: Deployment
      name: tigera-operator
      namespace: tigera-operator
    - kind: Installation
      name: default
