---
- name: Download Helm 3 binary
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: '/tmp/get_helm.sh'
    mode: '700'
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 3
  changed_when: false

- name: Install Helm 3 binary
  command: /tmp/get_helm.sh
  changed_when: false

- name: Download Flux binary
  get_url:
    url: https://fluxcd.io/install.sh
    dest: '/tmp/install.sh'
    mode: '700'
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 3
  changed_when: false

- name: Install Flux binary
  command: /tmp/install.sh
  changed_when: false
