---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin
spec:
  interval: 30m
  chart:
    spec:
      chart: pgadmin4
      version: 1.28.0
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    nameOverride: pgadmin
    strategy:
      type: Recreate
    serverDefinitions:
      enabled: true
      servers:
        cloudnative-pg:
          Name: "cloudnative-pg"
          Group: "Servers"
          Port: 5432
          Username: "postgres"
          Host: "postgres-r.database.svc.cluster.local"
          SSLMode: "prefer"
          MaintenanceDB: "postgres"
    annotations:
      configmap.reloader.stakater.com/reload: &configmap pgadmin
      secret.reloader.stakater.com/reload: &secret pgadmin
    env:
      email: ${CLOUDFLARE_EMAIL}
    existingSecret: pgadmin-secrets
    ingress:
      enabled: true
      ingressClassName: internal
      hosts:
        - host: pgadmin.${CLOUDFLARE_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
    networkPolicy:
      enabled: false
    persistentVolume:
      enabled: true
      existingClaim: pgadmin-config
    resources:
      requests:
        cpu: 15m
        memory: 183M
      limits:
        # cpu: 15m
        memory: 283M
