---
# yaml-language-server: $schema=https://kochhaus-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${CLOUDFLARE_DOMAIN}"
spec:
  secretName: "tls.${CLOUDFLARE_DOMAIN}"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${CLOUDFLARE_DOMAIN}"
  dnsNames:
    - "${CLOUDFLARE_DOMAIN}"
    - "*.${CLOUDFLARE_DOMAIN}"
