# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:L0PA+I1FRcoIlJLmJB3C73H8sbQHJw==,iv:TV+58pGNAZc5d3BXT4a1cM9a/f8/zeGdPU7TC4+6YVc=,tag:RKhhoSx+3IrwouacOxQOKw==,type:str]
    CLOUDFLARE_DOMAIN: ENC[AES256_GCM,data:HDKUYQifrSCfV0w=,iv:pF6+9vg1ZGWfqx3gb8G1bqEXeZH2+eZciZBCnwocyAc=,tag:ZNT/h8L/a1keZ2fepz52iw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zqydytfsqv3g789ud2jjhrflk445wcadnz0fccrf82zhwfwcgd4q404rtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3OUd6Sk1uaUczR09iVFYx
            d3Z1eXZOZVRDekxEQk4xcFRTNFc1V0Y2OGlFCjVhZy9QdG9TeHB1OFlsRW9pSlBQ
            cmQwM0s1MlcycWtaY1dEbGJmQ0U5cWMKLS0tIEJFOFE5NUxhMkpYZ1JtVVE0MHJI
            eDJMZWZNOGdQM3FRRmVEZWx2Mm9vSlEK3uSTk1EYIBaEdN+TX8tyGxbc5kzII1iq
            w1Hn0+kzmPlcs4W5BJvg1OQjwMvAfDz1eWu41zHj3dKJUebV3gW03A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-25T00:44:03Z"
    mac: ENC[AES256_GCM,data:Pz0h65JKAfMuQrXZLzeEiXw+cbs3xvbyaCGbFM/iShDsxm72Izf5UukL9VE3SVaZVJcmCpg+3vm3vEjdsYhiC2dUy0Qbbsz05npXaFCSUSUjfABZetsS1SPc1zjCpQHxhPqOMcXqGEFlbVfHgY5gDp7zKiRBGCGSHBSa5Mf2w28=,iv:kJIdg87w2BCEHzKel0UYqGaukOXLJ/61akEIh5ojYdI=,tag:u1eP9qyR3uzM2THazCicyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
