# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:cjG5xGx+dN9QfZOl45867X0/uPkjpg==,iv:i8W0y+qBCyvWKjb7zs0rKUQJ764m+LpYMf9SFdNbA6I=,tag:KNwnqBUDNRJdEjYD8e2pOg==,type:str]
    CLOUDFLARE_DOMAIN: ENC[AES256_GCM,data:nNl5No5mPSpKbus=,iv:srYcmQ5uZeFgLKYLPHxlWFDd114JySmcBUeNBN6aJSI=,tag:AmmzSwL1i9Ov5MvvSHVN4Q==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:7xloc1Ia3PG2DupjvLmHxaM3OBdS0r9vGyboZ2rrM0mN1yiG,iv:406c5a4CBKcPmH9b1Yho6ibhS8olWOky3k95nOjdU44=,tag:uvwBqSJSsKwl43BapziCGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zqydytfsqv3g789ud2jjhrflk445wcadnz0fccrf82zhwfwcgd4q404rtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdWVpcjg2NmZnVzMyL3Nu
            VEh3ekdGOHlYMmRPT1BCa21DOVRrZzVyNFZzCkZmK3FWVFNkQ09iWjJlbG9YOHor
            Qjg2NFk0R2tTSzZQeG5EaHB6NEROZW8KLS0tIFBndWI5elp1c0JnVElqdjVJMThR
            YU4zcDhwL3g5NWlXaGJnWWlLLzRQdTAKmJtBrOEfMXxObOFMaFIsOGQ1HgSbzFDg
            wwQqoO4c2k46yozwjrCGcmqnYyqVMjLUML2mLirec4u0YMBOJviSgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-12T01:02:53Z"
    mac: ENC[AES256_GCM,data:JeLAyDkVn2f3kp53bBAXyvWUxD64ld20dfLlErNphslLAIEBGEgQyyrnOKcNhsurDA9ehkaiWiNeNgyru+g7JP4EyissQYzJJ1W+shNkrwrxHib3G8nTdPLNosvPSENvu+AO/7jOYYWUB7bCWVrs2iGp4tMbVvOmr0g6N6PUR4M=,iv:1hf70au7Ijuc0H0O5Kr+cCQd5Cxhzm3PE3g7nhHmV7M=,tag:J/zACoUUdAvo5UpsPfunYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
