# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:otNiZJIqi2RvhCCBA8DE64A9ot3DMw==,iv:K8mQieRpnWFw6hFCIzYhu7oWksVmNDN0C+42Gwp4oxo=,tag:VHdWkuVLqrBnDgWXjm6g6g==,type:str]
    CLOUDFLARE_DOMAIN: ENC[AES256_GCM,data:UKYvdBxGQLIuy30=,iv:tGZ39mFLorX76GnFFxP8SR5d5s9wsraAWbrZ2FsQDfQ=,tag:YP5gF8Q1g6q83PTk928BAQ==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:gtkCxABHnboGi4NpkkBQ34q2SYggaERuie0BdG90JPysp4vj,iv:sY0KQF8YI3N5z5yjy1fQYExStAdzOpwfub+YS5PFQLE=,tag:nhjcM4ZWeplDcmEnXX0hFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zqydytfsqv3g789ud2jjhrflk445wcadnz0fccrf82zhwfwcgd4q404rtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbGxZUnRoSDIrU2xqQlRQ
            cW95dVJaWXNEM29oZ3F3L0drOWVmN085cjNrCnBWTWlMMG5NN2NHWWQ1WWtVMU9i
            SXU3M3hQalBBNjFvaGdJRENaS1hrVWsKLS0tIENHdkc0MjBXY1V3MVVsbjFwTHZO
            bWhOcy8xR0ZENTNUT2VQLy9KaUl6dUUK/Yqyasu/ADP1YDhD2koMEU27ums0zhE5
            25Q7wT+WbTz/IaRowFlEX6G2jV6gSnwe+Vu9755pCRVObb4ZUyO1IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-19T20:27:59Z"
    mac: ENC[AES256_GCM,data:AiTXbtKM+UBWLcE95zIfDm5DvNxS75tZRQp4FYoAx1TzXiSOWHItu51f+0llifh+GoeubY0IZjM+tpSd8/T4AgL5X9+lU71qebHzsu9cpBWWqlnQbExE94+G6B3UtmXBCUtXz9qwyixjyoDiLT3szQTlF+3ZGwLkoEquDBCDqmw=,iv:eiSO0Obt3/Vuaq9czOWBLjYuafw/ycUhJXfVTY7Cf6g=,tag:kugZLMK5C3oyUaR7fkEI3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
