---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Paris"
  METALLB_IP_RANGE: 192.168.1.200-192.168.1.210
  METALLB_INGRESS_ADDR: 192.168.1.210
  DISCORD_CHANNEL: "cicd"
