---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:

    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: docker.io/plexinc/pms-docker
      tag: 1.32.1.6999-91e1e2e2c

    env:
      TZ: "${TIMEZONE}"
      PLEX_UID: 0
      PLEX_GID: 0

    service:
      main:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${SVC_PLEX_ADDR}
        externalTrafficPolicy: Local
        ports:
          http:
            port: 32400

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host "plex.${CLOUDFLARE_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
      media:
        enabled: true
        type: nfs
        server: "${NFS_SERVER_ADDR}"
        path: /nas/Apps/Media
        mountPath: /media
      transcode:
        enabled: true
        type: emptyDir
      local:
        enabled: true
        type: emptyDir
        mountPath: /.local

    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

    nodeSelector:
      node-role.kubernetes.io/worker: "true"

    resources:
      requests:
        cpu: 4
        memory: 500Mi
      limits:
        memory: 700Mi
        cpu: 7
