---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-cloudflare
  namespace: networking
spec:
  interval: 30m
  releaseName: *app
  chart:
    spec:
      chart: external-dns
      version: 1.13.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  maxHistory: 1
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    logLevel: debug
    interval: 2m
    provider: cloudflare
    policy: sync
    txtPrefix: "k8s."
    fullnameOverride: *app
    sources:
      - ingress
      - crd
    domainFilters:
      - "${CLOUDFLARE_DOMAIN}"
    env:
      - name: CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            name: external-dns-cloudflare-secret
            key: email
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            name: external-dns-cloudflare-secret
            key: apiKey
    extraArgs:
      - --annotation-filter=external-dns.alpha.kubernetes.io/target
      - --cloudflare-proxied
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
    metrics:
      enabled: true
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: external-dns-cloudflare-secret
