---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pgadmin-secret
    creationPolicy: Owner
  data:
    - secretKey: email
      remoteRef:
        key: pgadmin
        property: email
    - secretKey: password
      remoteRef:
        key: pgadmin
        property: password
    - secretKey: PGADMIN_DEFAULT_PASSWORD
      remoteRef:
        key: pgadmin
        property: PGADMIN_DEFAULT_PASSWORD
