---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: pgadmin4
      version: 1.15.3
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    nameOverride: pgadmin
    strategy:
      type: Recreate
    env:
      email: ${PGADMIN_ADMIN_EMAIL}
    existingSecret: pgadmin-secret
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: &host "pgadmin.${CLOUDFLARE_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    networkPolicy:
      enabled: false
    persistentVolume:
      enabled: true
      storageClass: longhorn
      accessModes:
        - ReadWriteOnce
      size: 200Mi
