---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./helmrelease.yaml
  - ./secrets.sops.yaml
labels:
  - pairs:
      app.kubernetes.io/name: pgadmin
      app.kubernetes.io/instance: pgadmin
