# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secret
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:8TnkcUz+wD1MiiFQtHh3ysRFEY9xlWVU6WqGWQI=,iv:PmbgOJAa8b8vDN841/v0Bj0A76E59DS/GHBd8vIz0J8=,tag:v9OIwd7oNRdTQI7BwyvroQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zqydytfsqv3g789ud2jjhrflk445wcadnz0fccrf82zhwfwcgd4q404rtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SmF3cTJqQVV6S1YxQWgw
            OWtHM0tGS3BQL3paaG9tVDdHZi9MNjZNcGhVClNOU0NnelpRTHlzNlpEOFo0RDcv
            TzFlY1RMckMxdHloRUxkbE80OGtvNVkKLS0tIHM5K1pRRStvRGF4UHJvaWZoWHJV
            SDh0RWNFSzZyR1dpQzl2WTUxTyt3bXMKJfdbsE4bnNIgk3dJmx6+jFSifUhClQl1
            PaRIFiBJgcHUgk7aHjtNpr9AdwL0he0r3Tb00VhMZMjPw2XRbQMpaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-29T21:20:20Z"
    mac: ENC[AES256_GCM,data:2oAcLYSWn1ovaeQhKTrCI4yIeRkZZ/45Cl4fJtQpYuNap2dyV6yeXqaVp8GgwvHJsyBTbHPhna5h3FyqyLqiTdRUWXb/A0bUHr2Pu7nxJmfsxQTuhnSKUPAgbpujUoiGWpgAgYgTzZZ+mrSMRM866maJUS3+AoJnJfHReBqhqLg=,iv:dbTAKfzmvIita2fTXTJ9te+Yo1n/rf5wbazmWWROHiw=,tag:C0SIZyXwoFgnqsCEO4yf/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
