---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-grafana
  namespace: flux-system
spec:
  path: ./kubernetes/apps/monitoring/grafana/app
  dependsOn:
    - name: cluster-apps-external-secrets-stores
  prune: true
  sourceRef:
    kind: GitRepository
    name: nexus-repository
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: grafana
      namespace: monitoring
  interval: 15m
  retryInterval: 1m
  timeout: 5m
