---
k3s_release_version: "v1.27.3+k3s1"
k3s_install_hard_links: true
k3s_skip_validation: false
k3s_become: true
k3s_debug: false
k3s_etcd_datastore: false
k3s_server_manifests_templates:
  - calico-installation.yaml.j2
  - coredns-helmchart.yaml.j2
# /var/lib/rancher/k3s/server/manifests
k3s_server_manifests_urls:
  - url: https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/tigera-operator.yaml
    filename: calico-tigera-operator.yaml

longhorn_data_folder: /var/lib/longhorn/
