---
apt_install_packages:
  - vim
  - curl
  - wget
  - nano
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - python3-pip
  - python3-setuptools
  - tmux
  - net-tools
  - arptables
  - gdisk
  - htop
  - unattended-upgrades
  - unzip
  - sudo

apt_remove_packages:
  - cloud-init
  - cloud-guest-utils
  - cloud-initramfs-copymods
  - cloud-initramfs-dyn-netconf
  - friendly-recovery
  - fwupd
  - landscape-common
  - lxd-agent-loader
  - ntfs-3g
  - open-vm-tools
  - popularity-contest
  - snapd
  - sosreport
  - ubuntu-advantage-tools
  - ufw
  - vim.tiny
  - unattended-upgrades
  - apparmor

server_distribution: jammy
timezone: "Europe/Paris"

# Add cloudflare ntp server
ntp_servers:
  primary:
    - "time.cloudflare.com"
  fallback:
    - "0.us.pool.ntp.org"
    - "1.us.pool.ntp.org"
    - "2.us.pool.ntp.org"
