---
public_ssh_keys:
  -"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICMXNU/Lt9esC8WL5I0GXwop3mS92S2grZcTxhN8fh1m spike@shiva"
server_distribution: jammy
apt_install_packages:
  - curl
  - wget
  - nano
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - python3-pip
  - python3-setuptools
  - tmux
  - net-tools
  - arptables
  - gdisk
  - fdisk
  - htop
  - unattended-upgrades
  - unzip
  - sudo
  - python3-kubernetes
  - python3-yaml
  - smartmontools

apt_remove_packages:
  - cloud-init
  - cloud-guest-utils
  - cloud-initramfs-copymods
  - cloud-initramfs-dyn-netconf
  - friendly-recovery
  - fwupd
  - landscape-common
  - lxd-agent-loader
  - ntfs-3g
  - open-vm-tools
  - popularity-contest
  - snapd
  - sosreport
  - ubuntu-advantage-tools
  - ufw
  - vim.tiny
  - unattended-upgrades
  - apparmor

timezone: "Europe/Paris"

# Add cloudflare ntp server
ntp_servers:
  primary:
    - "time.cloudflare.com"
  fallback:
    - "0.us.pool.ntp.org"
    - "1.us.pool.ntp.org"
    - "2.us.pool.ntp.org"
