---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dnsendpoint.yaml
  - helmrelease.yaml
  - externalsecret.yaml

configMapGenerator:
  - name: cloudflared-config
    files:
      - resources/config.yaml
generatorOptions:
  disableNameSuffixHash: true
