---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gatus-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PUSHOVER_APP_TOKEN: "{{ .GATUS_PUSHOVER_API_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: gatus
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .GATUS_DB_USER }}"
        INIT_POSTGRES_PASS: "{{ .GATUS_DB_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .PG_SUPER_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .PG_SUPER_USER }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: pushover
    - extract:
        key: gatus
