---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector-agent
  namespace: monitoring
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: vector-aggregator
  values:
    image:
      repository: timberio/vector
      tag: 0.30.0-debian
    role: Agent
    controller:
      type: daemonset
      strategy: RollingUpdate
    args: ["--config", "/etc/vector/vector.yaml"]
    env:
      VECTOR_SELF_NODE_NAME:
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: spec.nodeName
      VECTOR_SELF_POD_NAME:
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      VECTOR_SELF_POD_NAMESPACE:
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
    service:
      main:
        enabled: false
    serviceAccount:
      create: true
      name: vector-agent
    securityContext:
      privileged: true
    tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
    persistence:
      config:
        enabled: true
        type: configMap
        name: vector-agent-configmap # overriden by kustomizeconfig
        subPath: vector.yaml
        mountPath: /etc/vector/vector.yaml
        readOnly: true
      data:
        enabled: true
        type: emptyDir
        mountPath: /vector-data-dir
      var-log:
        enabled: true
        type: hostPath
        hostPath: /var/log
        hostPathType: Directory
        mountPath: /var/log
        readOnly: true
