---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-plex
  namespace: flux-system
spec:
  path: ./kubernetes/main/apps/media/plex/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repository
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  wait: false
