---
tunnel: ${CLOUDFLARE_TUNNEL_ID}
credentials-file: /etc/cloudflared/cred.json
originRequest:
  connectTimeout: 30s
warp-routing:
  enabled: false
no-autoupdate: true

# Internet --> cloudflared tunnel --> local DNS (split-horizon DNS) --> ingress --> service
ingress:
  - hostname: "*.${CLOUDFLARE_DOMAIN}"
    service: https://ingress-nginx-controller.networking
    originRequest:
      noTLSVerify: true
  - service: http_status:404
