---
tunnel: ${CLOUDFLARE_TUNNEL_ID}
credentials-file: /etc/cloudflared/cred.json
originRequest:
  connectTimeout: 30s
warp-routing:
  enabled: false

ingress:
  - service: https://ingress-nginx-controller.networking
    originRequest:
      noTLSVerify: true
