---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - ./dnsendpoint.yaml
  - ./helmrelease.yaml
  - ./externalsecret.yaml

configMapGenerator:
  - name: cloudflared-config
    files:
      - ./config/config.yaml
generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      app.kubernetes.io/name: cloudflared
      app.kubernetes.io/instance: cloudflared
