---
- name: Reboot Nexus
  hosts: nexus
  become: true
  tasks:
    - name: Reboot Nexus
      ansible.builtin.reboot:
        msg: "Reboot Nexus by Ansible"
        pre_reboot_delay: 5
        post_reboot_delay: 10
        test_command: "whoami"
