---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app botkube
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: botkube
      version: v0.18.0
      sourceRef:
        kind: HelmRepository
        name: botkube
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  valuesFrom:
    - targetPath: communications.default-group.discord.token
      kind: Secret
      name: botkube-discord-secret
      valuesKey: token
    - targetPath: communications.default-group.discord.botID
      kind: Secret
      name: botkube-discord-secret
      valuesKey: botId
    - targetPath: communications.default-group.discord.channels.default.id
      kind: Secret
      name: botkube-discord-secret
      valuesKey: channelId
  values:
    settings:
      clusterName: default
      configWatcher: true
    communications:
      default-group:
        discord:
          enabled: true
          channels:
            default:
              notification:
                disabled: false
              bindings:
                executors:
                  - kubectl-read-only
                sources:
                  - crds
                  - k8s-recommendation-events
                  - k8s-all-events
                  - k8s-err-events
                  - k8s-err-with-logs-events
    executors:
      kubectl-read-only:
        kubectl:
          enabled: true
    actions:
      "describe-created-resource":
        enabled: false
      "show-logs-on-error":
        enabled: true
    sources:
      crds:
        displayName: CRDS
        kubernetes:
          enabled: true
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
          resources:
            - name: helm.toolkit.fluxcd.io/v2beta1/helmreleases
            - name: source.toolkit.fluxcd.io/v1beta2/helmcharts
            - name: kustomize.toolkit.fluxcd.io/v1beta2/kustomizations
            - name: notification.toolkit.fluxcd.io/v1beta1/alerts
            - name: monitoring.coreos.com/v1/podmonitors
            - name: monitoring.coreos.com/v1/servicemonitors
      k8s-recommendation-events:
        kubernetes:
          enabled: true
      k8s-all-events:
        kubernetes:
          enabled: true
          resources:
            - type: v1/pods
            - type: v1/services
            - type: networking.k8s.io/v1/ingresses
            - type: v1/nodes
            - type: v1/namespaces
            - type: v1/configmaps
            - type: rbac.authorization.k8s.io/v1/roles
            - type: rbac.authorization.k8s.io/v1/rolebindings
            - type: rbac.authorization.k8s.io/v1/clusterrolebindings
            - type: rbac.authorization.k8s.io/v1/clusterroles
            - type: apps/v1/daemonsets
            - type: apps/v1/deployments
            - type: apps/v1/statefulsets
      k8s-create-events:
        kubernetes:
          enabled: true
          resources:
            - type: v1/pods
            - type: v1/services
            - type: networking.k8s.io/v1/ingresses
            - type: v1/nodes
            - type: v1/namespaces
            - type: v1/configmaps
            - type: apps/v1/deployments
            - type: apps/v1/statefulsets
            - type: apps/v1/daemonsets
      k8s-err-events:
        kubernetes:
          enabled: true
      k8s-err-with-logs-events:
        kubernetes:
          enabled: true
