---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-portainer
  namespace: flux-system
spec:
  path: ./kubernetes/apps/monitoring/portainer/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: nexus-repository
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: portainer
      namespace: monitoring
  interval: 30m
  retryInterval: 1m
  timeout: 3m
