---
- name: Check if iptables is installed
  package:
    name: iptables
    state: present
  check_mode: true
  register: iptables_install_check

- name: Nuke Iptables if installed
  block:
    - name: "Flush the rules on nat table  all chains"
      shell: iptables -t nat -F

    - name: "Flush the rules on mangle table for all chains"
      shell: iptables -t mangle -F

    - name: "Flush on all chains for all tables"
      shell: iptables -F

    - name: "Clean all chains"
      shell: iptables -X
  when: not iptables_install_check.changed
