---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-tigera-operator
  namespace: flux-system
spec:
  path: ./kubernetes/main/apps/tigera-operator/tigera-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repository
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: tigera-operator
      namespace: tigera-operator
  interval: 30m
  retryInterval: 1m
  timeout: 3m
