---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-metrics-server
  namespace: flux-system
spec:
  path: ./kubernetes/main/apps/kube-system/metrics-server/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repository
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: metrics-server
      namespace: kube-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
