---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatus
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/twin/gatus
      tag: v5.4.0

    initContainers:
      01-init-db:
        image: ghcr.io/onedr0p/postgres-init:14.8
        imagePullPolicy: IfNotPresent
        envFrom: &envFrom
          - secretRef:
              name: gatus-secret

    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    env:
      TZ: ${TIMEZONE}
      GATUS_CONFIG_PATH: /config
      CLOUDFLARE_DOMAIN: ${CLOUDFLARE_DOMAIN}

    envFrom: *envFrom

    service:
      main:
        ports:
          http:
            port: 8080

    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${CLOUDFLARE_DOMAIN}"
        hosts:
          - host: &host status.${CLOUDFLARE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    serviceAccount:
      create: true
      name: gatus

    persistence:
      config:
        enabled: true
        type: emptyDir
      config-file:
        enabled: true
        type: configMap
        name: gatus-configmap
        mountPath: /config/config.yaml
        subPath: config.yaml
        readOnly: true
