---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app lldap
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 1
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    initContainers:
      01-init-db:
        image: ghcr.io/onedr0p/postgres-init:14.8
        imagePullPolicy: IfNotPresent
        envFrom: &envFrom
          - secretRef:
              name: lldap-secret
    controller:
      replicas: 1
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/lldap/lldap
      tag: v0.4.3
    env:
      TZ: ${TIMEZONE}
      LLDAP_HTTP_PORT: &port 80
      LLDAP_HTTP_URL: https://lldap.${CLOUDFLARE_DOMAIN}
      LLDAP_LDAP_PORT: &ldapPort 389
      LLDAP_LDAP_BASE_DN: dc=home,dc=arpa
    envFrom: *envFrom
    service:
      main:
        ports:
          http:
            port: *port
          ldap:
            enabled: true
            port: *ldapPort
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host "lldap.${CLOUDFLARE_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        memory: 100Mi
