---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-stores
  path: ./kubernetes/main/apps/cert-manager/cert-manager/app
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: homelab-repository
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cert-manager-issuers
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cert-manager
  path: ./kubernetes/main/apps/cert-manager/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repository
  interval: 30m
  retryInterval: 1m
  timeout: 3m
