kind: Secret
ansible_user: ENC[AES256_GCM,data:FAMB7hk=,iv:SMBmcfTGzcTFfddSVqsza9OTVmZ5/h5sI2fiARxx4yg=,tag:pyGMk6qc+7yI/dZOD0zXXg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:i2kiawffKj8gbsGeYKucS2JbqIXeJOjM0OUdk4k8qSVdy96HceQM8kLpYcPUPmIcNIqqT68cSLJexIYP,iv:8HfMtY3eMDswyLd42M3JksnQFCbHAfDqFYGKciyEVnk=,tag:8jVCIaWus+Dqd6l/776YDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zqydytfsqv3g789ud2jjhrflk445wcadnz0fccrf82zhwfwcgd4q404rtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5L2U1MDl5dmpMS0xHSjJx
            RXBtODhyVUJFWitQK1Q5S2dXVTVNWjdjU2hZCnlFNlVRVHJsdGh1RjkrM2U3MTVv
            ZjFwL2RDaG1Dc3VhVklFeTBVdFZ6dTAKLS0tIGRublJOQW9zbWpTVGg2MnRQVG5J
            Si9PYlR4aGt2MllRajRaVG10c3FsclEKBwYRrjeAeGZVssrD3lyZjaH3l3NNCiP3
            p0qm0DKeytzUCdE7PqxJY7L6k4HgzAeAP23Woucu0B6fExfdfcsl/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-09T00:08:00Z"
    mac: ENC[AES256_GCM,data:dzYjEdT7xi+VZC7DfCV6TfjqqwYCReDNujSm/ccAAheNqrfeB/unsJE1KKd25nfnmZ5FJKHAd0awZ8DcrYV1C5IjyT2TxBGbyAKKds7hdjp144wB8H62x6PD9EPZufyfga+7Papud3Y6+DW8v2Fnw9OE8D/+a4PEaRq1kG68GMc=,iv:Kk3lKAgLPz5vJz8ouZaUsv0oPbenE8uWaxDoVoXQGnk=,tag:fbgMsFAC9pcq4tlK8TT2Mg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
